--Agregar los atributos de auditorias
ALTER TABLE FIDE_CANTONES_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_CANTONES_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_CANTONES_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_CANTONES_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_CANTONES_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_CATEGORIAS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_CATEGORIAS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_CATEGORIAS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_CATEGORIAS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_CATEGORIAS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_CLIENTES_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_CLIENTES_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_CLIENTES_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_CLIENTES_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_CLIENTES_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_DETALLES_PEDIDO_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DETALLES_PEDIDO_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DETALLES_PEDIDO_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_DETALLES_PEDIDO_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_DETALLES_PEDIDO_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_DIRECCIONES_CLIENTE_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_CLIENTE_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_CLIENTE_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_DIRECCIONES_CLIENTE_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_DIRECCIONES_CLIENTE_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_DIRECCIONES_EMPLEADO_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_EMPLEADO_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_EMPLEADO_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_DIRECCIONES_EMPLEADO_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_DIRECCIONES_EMPLEADO_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_DIRECCIONES_PEDIDO_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_PEDIDO_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_PEDIDO_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_DIRECCIONES_PEDIDO_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_DIRECCIONES_PEDIDO_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_DISTRITOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DISTRITOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_DISTRITOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_DISTRITOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_DISTRITOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_EMPLEADOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_EMPLEADOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_EMPLEADOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_EMPLEADOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_EMPLEADOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_ESTADOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_ESTADOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_ESTADOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_ESTADOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_ESTADOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_FACTURAS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_FACTURAS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_FACTURAS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_FACTURAS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_FACTURAS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_LICENCIAS_EMPLEADO_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_LICENCIAS_EMPLEADO_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_LICENCIAS_EMPLEADO_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_LICENCIAS_EMPLEADO_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_LICENCIAS_EMPLEADO_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_LICENCIAS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_LICENCIAS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_LICENCIAS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_LICENCIAS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_LICENCIAS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_PEDIDOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PEDIDOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PEDIDOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_PEDIDOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_PEDIDOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_PRODUCTOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PRODUCTOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PRODUCTOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_PRODUCTOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_PRODUCTOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_PROVINCIAS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PROVINCIAS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PROVINCIAS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_PROVINCIAS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_PROVINCIAS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_PUESTOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PUESTOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_PUESTOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_PUESTOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_PUESTOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_ROLES_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_ROLES_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_ROLES_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_ROLES_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_ROLES_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_TIPOS_CARGA_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_TIPOS_CARGA_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_TIPOS_CARGA_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_TIPOS_CARGA_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_TIPOS_CARGA_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_USUARIOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_USUARIOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_USUARIOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_USUARIOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_USUARIOS_TB ADD (ACCION VARCHAR2(100));
/
ALTER TABLE FIDE_VEHICULOS_TB ADD (CREATED_BY VARCHAR2(100));
ALTER TABLE FIDE_VEHICULOS_TB ADD (LAST_UPDATED_BY VARCHAR2(100));
ALTER TABLE FIDE_VEHICULOS_TB ADD (CREATION_DATE TIMESTAMP);
ALTER TABLE FIDE_VEHICULOS_TB ADD (LAST_UPDATE_DATE TIMESTAMP);
ALTER TABLE FIDE_VEHICULOS_TB ADD (ACCION VARCHAR2(100));
/
--CREACION DE TRIGERS PARA EL CREADO_POR, FECHA_CREACION,
--MODIFICADO_POR, FECHA_MODIFICACION, ACCION, ID_ESTADO
--TRIGGERS PARA VER LA FECHA DE INSERCION O MODIFICACION
CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLES_PEDIDO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLES_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_CLIENTE_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_CLIENTE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_EMPLEADO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_EMPLEADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_PEDIDO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_PEDIDO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_LICENCIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_EMPLEADO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_LICENCIAS_EMPLEADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PUESTOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PUESTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOS_CARGA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPOS_CARGA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_VEHICULOS_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_VEHICULOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATION_DATE := SYSTIMESTAMP;
    ELSE
        :NEW.LAST_UPDATE_DATE := SYSTIMESTAMP;
    END IF;
END;
/


--TRIGGER PARA VER QUIEN INSERTO O MODIFICO
CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLES_PEDIDO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLES_PEDIDO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_CLIENTE_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_CLIENTE_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_EMPLEADO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_EMPLEADO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_PEDIDO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_PEDIDO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.CREATED_BY:=USER;
ELSE
    :NEW.LAST_UPDATED_BY:=USER;
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_LICENCIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_EMPLEADO_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_LICENCIAS_EMPLEADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_PUESTOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PUESTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_TIPOS_CARGA_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPOS_CARGA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_VEHICULOS_TB_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_VEHICULOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_BY := USER;
    ELSE
        :NEW.LAST_UPDATED_BY := USER;
    END IF;
END;
/ 


--TRIGGER PARA EL ATRIBUTO ACCION

CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLES_PEDIDO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLES_PEDIDO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_CLIENTE_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_CLIENTE_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_EMPLEADO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_EMPLEADO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_PEDIDO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_PEDIDO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_LICENCIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_EMPLEADO_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_LICENCIAS_EMPLEADO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PUESTOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PUESTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOS_CARGA_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPOS_CARGA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_VEHICULOS_TB_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_VEHICULOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.ACCION:='INSERT';
ELSE
    :NEW.ACCION:='UPDATE';
END IF;
END;
/

---TRIGGER PARA EL ESTADO
 CREATE OR REPLACE TRIGGER FIDE_CANTONES_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/ 

CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLES_PEDIDO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DETALLES_PEDIDO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_CLIENTE_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_CLIENTE_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_EMPLEADO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_EMPLEADO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_PEDIDO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_PEDIDO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_EMPLEADOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_EMPLEADO_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_LICENCIAS_EMPLEADO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_LICENCIAS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_LICENCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PUESTOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_PUESTOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPOS_CARGA_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_TIPOS_CARGA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/

CREATE OR REPLACE TRIGGER FIDE_VEHICULOS_TB_ESTADO_TRG
BEFORE INSERT ON FIDE_VEHICULOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := 7;
END;
/